### ISSUE TITLE
Language Proficiency Page

### ISSUE THREAD

**Issue by cattuong** [tnguyen14/seo-website#10]
1. Probably should clarify whether it is Fluent Writing and/or Speaking and/or Reading as a lot of our candidates are Vietkieu and while they are fluent speaking, they have limited Reading and Speaking skill.
2. Probably besides Fluent and Basic Understanding, we can add "Intermediate"
3. Someone brought up back then that probably Spanish and French are not necessary cause the internships will be in Vietnamese and English

**Comment by tnguyen14** [comment]
Please repost to the right repo.

**Comment by cattuong** [comment]
Hi Tri,

Could you please move these posts to the right repo? I am very sorry as I
mistakenly thought the link for the website as also the link for the
application system. However, I have posted these twice now and really do
not have time to screen shot everything and post them again. Thus, it would
be great if you could do me this favor.

If there is absolutely no way to move these post to the right repo, I will
try later next week.

Thanks
Cat Tuong

On Thu, Dec 5, 2013 at 5:53 PM, Tri Nguyen notifications@github.com wrote:

> Closed #10 https://github.com/tnguyen14/seo-website/issues/10.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/tnguyen14/seo-website/issues/10
> .

## 

Cat Tuong Nguyen
University of Nebraska-Lincoln
Biological Systems Engineering
kat1812@gmail.com
