### ISSUE TITLE
Citizenship/Country of Residence

### ISSUE THREAD

**Issue by cattuong** [tnguyen14/seo-website#11]
When I add French as Citizenship, it automatically updates Country of Residence. However, there is no country as French ... So should I add "France"?

![screen shot 2013-12-04 at 9 01 42 am](https://f.cloud.github.com/assets/6106864/1676037/478d8974-5d13-11e3-9835-9400308fbf77.jpg)

**Comment by tnguyen14** [comment]
Please repost to the right repository.
