### ISSUE TITLE
Citizenship

### ISSUE THREAD

**Issue by cattuong** [tnguyen14/seo-website#12]
If I add France, then it displays "The document "France" already exists" ... So I had to add French. Not sure why cause France was not on the drop down list
![screen shot 2013-12-04 at 9 01 25 am](https://f.cloud.github.com/assets/6106864/1676031/3b2753d6-5d13-11e3-8ede-3a2cdaf988ef.jpg)

**Comment by tnguyen14** [comment]
Please repost to the right repository.
